<?php 
/**
 * @package: Dadi Cookie Consent Lite
 * Block PHP
 */

if( ! defined( 'DADICC_ALLOW' ) ) {
    exit();
}

/**
 * Load block php module
 *
 */
function dadicc_get_module_block_php( $options ) { ?>

    <?php if( (bool) dadicc_is_premium_features() === false ) : ?>
    
        
        <div class="dadicc-info">  
            <p>
                <?php if( (bool) $options['disable_php_block'] === false ) :
                    esc_html_e( 'Javascript and Iframes have been blocked by default. Only the essential scripts for banner and consent will be loaded.', DADICC_DOMAIN );
                else : 
                    esc_html_e( 'Javascript and Iframes have been unlocked. Are you sure you want this?', DADICC_DOMAIN );
                endif; ?>
            </p>
        </div>
    
    <?php else : ?>
    
        <!-- Keep essential js scripts -->

        <h3 class="legend"><?php esc_html_e('Javascript Blocking', DADICC_DOMAIN ); ?></h3>
        <p>
            <?php dadicc_display_premium_message(); ?>
            <input type="checkbox" id="enable-script-block" name="" value="1" disabled>
            <label for="enable-script-block"><?php esc_html_e('Enable scripts blocking', DADICC_DOMAIN ); ?></label>
            <span class="dadicc-infos dashicons-before dashicons-info"><?php esc_html_e( 'Only the essential scripts for banner and consent, and all bypassed js will be loaded.', DADICC_DOMAIN ); ?></span>
        </p>
        <p>
             <?php dadicc_display_premium_message(); ?>
        </p>
        <div class="services-group">
            <button type="button" class="button add-target buffer-script" disabled>
                <span class="dashicons dashicons-editor-code"></span>
                <?php esc_html_e('Add Kept Scripts', DADICC_DOMAIN ); ?>
            </button>
        </div>
        <p class="service-area" id="area-global-scripts">
            <span class="no-service-yet"><?php esc_html_e('No services yet!', DADICC_DOMAIN ); ?></span>
        </p>
        <p>
            <span class="dadicc-infos dashicons-before dashicons-info">
                <?php esc_html_e('Set target scripts to keep during the block, clicking in "Add Kept Scripts".', DADICC_DOMAIN ); ?>
            </span>
        </p>
    
        <!-- Block Iframe -->
    
        <h3 class="legend"><?php esc_html_e('Iframe Blocking', DADICC_DOMAIN ); ?></h3>
        <p>
            <?php dadicc_display_premium_message(); ?>
            <input type="checkbox" id="enable-iframe-block" name="" value="1" disabled>
            <label for="enable-iframe-block"><?php esc_html_e('Enable iframe blocking', DADICC_DOMAIN ); ?></label>
            <span class="dadicc-infos dashicons-before dashicons-info"><?php esc_html_e( 'Every content in the iframes will not be load.', DADICC_DOMAIN ); ?></span>
        </p>
        <p>
             <?php dadicc_display_premium_message(); ?>
        </p>
        <div class="services-group">
            <button type="button" class="button add-target buffer-iframe" disabled>
                <span class="dashicons dashicons-editor-code"></span>
                <?php esc_html_e('Add Kept Iframes', DADICC_DOMAIN ); ?>
            </button>
        </div>
        <p class="service-area" id="area-global-iframes">
            <span class="no-service-yet"><?php esc_html_e('No services yet!', DADICC_DOMAIN ); ?></span>
        </p>
        <p>
            <span class="dadicc-infos dashicons-before dashicons-info">
                <?php esc_html_e('Set target iframes to keep during the block, clicking in "Add Kept Iframes".', DADICC_DOMAIN ); ?>
            </span>
        </p>
        
    <?php endif; ?>
    
    <!-- Cookies -->
    
    <h3 class="legend"><?php esc_html_e('Cookies Blocking', DADICC_DOMAIN ); ?></h3>
    <p>
         <label>
             <input type="checkbox" id="all-blocked-cookies" name="dadicc_options[all_blocked_cookies]" value="1" <?php checked( $options['all_blocked_cookies'], 1 ); ?>>
             <?php printf( esc_html__('With the blocking action also remove existing cookies%s %s(not recommended)%s', DADICC_DOMAIN ), '<span class="dadicc-asterisk">*</span>', '<span class="recommended">', '</span>' ); ?>
             <span class="dadicc-infos dashicons-before dashicons-info"><?php esc_html_e( 'The removed cookies must be regenerated with the relative action (the simple unchecked is not enough to restore cookies)!', DADICC_DOMAIN ); ?></span>
             <span class="dadicc-note dashicons-before dashicons-admin-post"><?php printf( esc_html__('For security reasons, only works with cookies generated on %s.', DADICC_DOMAIN ), '<code>' . dadicc_get_site_domain(). '</code>' ); ?></span>
             <span class="dadicc-note dashicons-before dashicons-admin-post"><?php esc_html_e('Cookies block not seem to work with persistent cookies or cookies generated by javascript.', DADICC_DOMAIN ); ?></span>
         </label>
    </p>
    
    <!-- Disable PHP Block -->
    
    <h3 class="legend"><?php esc_html_e('Disable Blocking'); ?></h3>
    <p>
        <?php dadicc_display_premium_message( __('With full plugin, you can choose between complete deactivation, deactivation only for admin and activation.', DADICC_DOMAIN ) ); ?>
        <label><input type="checkbox" id="disable-php-block" name="dadicc_options[disable_php_block]" value="1" <?php checked( $options['disable_php_block'], 1 ); ?>> <?php esc_html_e( 'Disable blocking action. Only for debug.', DADICC_DOMAIN ); ?></label>
    </p>

<?php }

add_action( 'dadicc_block_php_module', 'dadicc_get_module_block_php');
